# Introduction to NumPy
## What we will cover?
* 1 creating single dimentional arrays
* 2 multidimentional array
* 3 randomly generated arrays
* 4 element wise operation
* 5 sumarizing operations

In [4]:
# Single Dimentional array
import numpy as np

In [5]:
# Create an array with all the elements to be zero

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.full(5, 2)


array([2, 2, 2, 2, 2])

In [14]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [11]:
np.empty(6)

array([3.47739925e-081, 6.00599911e-067, 1.34679237e+165, 2.14291146e+160,
       3.46797385e+179, 7.56571287e-307])

In [16]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
np.random.randint(0, 10)

7

In [21]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [23]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [26]:
np.arange(3, 31, 3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [36]:
# create an array with evenly spaced numbers within a specified range
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [42]:
print(np.nan)
print(np.inf)

print(np.sqrt(-1))
print(np.log(0))

nan
inf
nan
-inf


C:\Users\scile\AppData\Local\Temp\ipykernel_16124\3049807113.py:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\scile\AppData\Local\Temp\ipykernel_16124\3049807113.py:5: RuntimeWarning: divide by zero encountered in log
  print(np.log(0))


In [43]:
# Multidimentional array
# Create a 3*3 matrix with all elements zeros 
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:

arr = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)
# or 
arr.transpose()



[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
(3, 3)
2
9
int64
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]


array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18]])

In [69]:

arr = np.array([["prakash", "pathak", "hello"]])
print(arr)
print(arr.dtype)


[['prakash' 'pathak' 'hello']]
<U7


In [ ]:
# Create a multidimentional array with different elements
# Create the array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:")
print(arr)

# Replace 2 with 20
arr[0][1] = 20

print("\nModified array:")
print(arr)
# replace last row with 1
print("\nModify")
arr[2: ] = 1
print(arr)

# replace column 3 with 2
print("\nModify")
# arr[:,2] =2
arr[0:,2] =2
print(arr)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified array:
[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]

Modify
[[ 1 20  3]
 [ 4  5  6]
 [ 1  1  1]]

Modify
[[ 1 20  2]
 [ 4  5  2]
 [ 1  1  2]]


In [ ]:
# create a matrix 3*3 with all elements 10
arr = np.full((3, 3), 10)
print(arr)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [5]:
np.random.seed(42)
print(np.random.randint(0, 100, size=5))

[51 92 14 71 60]


# Day 13 NumPy

# Randomly generated arrays
* Numpy can cteate arrays filled with random numbers
* To ensure the reproductibility, you can seed using np.random.seed()
* It will generate the exact same random number for each executions.
* If you remove or change the seed values, the sequence of random numbers will be changed

In [86]:
import numpy as np
# np.random.seed(42)
np.random.rand(5)
np.random.randint(5)


0

In [90]:
# create random matrix with normal distribution
np.random.randn(5, 4)

array([[ 0.45293633, -0.16606091,  0.21493883, -2.02231493],
       [-0.94305681,  1.40395874, -0.0185508 , -1.67350462],
       [-1.07253183, -0.99258618,  0.10234768, -0.43260928],
       [-0.6591823 ,  0.0039373 ,  0.4777541 , -0.25902864],
       [-0.57470921, -0.42149822,  0.33982096, -0.00738015]])

In [ ]:
# create a matrix with random integers
np.random.randint(low=0, high=100, size=(5,2))

array([[ 2, 19],
       [58, 35],
       [18, 89],
       [66, 18],
       [19, 95]], dtype=int32)

In [152]:
# create a matrix with random integers
np.random.seed(24)
np.random.randint(low=0, high=20, size=(3,3))

array([[ 2,  3,  0],
       [17, 17,  1],
       [ 4, 15,  4]], dtype=int32)

In [153]:
# create a matrix with random integers
np.random.seed(20)
np.random.randint(low=0, high=20, size=(3,3))

array([[ 3, 15,  9],
       [11,  7,  2],
       [ 0,  8, 19]], dtype=int32)

In [174]:
# create a 1D NumPy array with numbers from 1 to 20, and then reshape it into a 4*5 matrix.

# Create a 1D array with numbers from 1 to 20
arr = np.arange(1, 21)
print(arr)
print()

# Reshape it into a 4x5 matrix
arr = arr.reshape(4, 5)

print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [190]:
# Fron the matrix create in Question 1, exact: 
# The second row
second_row = arr[1]
print(second_row)

print()

# the last column
last_column = arr[:,4]
print(last_column)
print()

# A submatrix containing rows 2 and 3 columns 1 to 3
submatrix = arr[1:3, 0:3]
print(submatrix)
print()

sub = arr[1:3, 2:]
print(sub)
print()

collen = len(arr[0])
print(collen)
print()
ar = arr[0:2, 1:3]
print(ar)



[ 6  7  8  9 10]

[ 5 10 15 20]

[[ 6  7  8]
 [11 12 13]]

[[ 8  9 10]
 [13 14 15]]

5

[[2 3]
 [7 8]]


In [ ]:
a = np.arange(5)
b = (10 + (a*2))
print(a)
print(b)
print(a + b) 
print(a * b)  # element wise operation not matrix operation

mylist = [0, 1, 2, 3, 4]
print(mylist*2) 


[0 1 2 3 4]
[10 12 14 16 18]
[10 13 16 19 22]
[ 0 12 28 48 72]
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]


In [202]:
# comparision operator
a == b
a>=2

array([False, False,  True,  True,  True])

In [207]:
# summarizing of the data 
# numpy provides function for sumarizing array data
a = np.array([1,2,3,4,5])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.std())
print(a.var())
print(a.cumsum())
print(a.cumprod())



1
5
15
3.0
1.4142135623730951
2.0
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [3]:
# Class assignment
# 1. Perform element-wise addition, multiplication of arrays a = [2, 4, 6, 8] and b = [1, 3, 5, 7]
import numpy as np
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

# Element-wise addition
add_result = a + b

# Element-wise multiplication
mul_result = a * b

print("Addition:", add_result)
print("Multiplication:", mul_result)

# 2. Generate an array of 15 random integers (10 - 100) and print values greater than 50.
import numpy as np

# Generate array of 15 random integers from 10 to 100 (inclusive)
arr = np.random.randint(10, 101, 15)

# Print the original array
print("Original array:", arr)

# Filter and print values greater than 50
greater_than_50 = arr[arr > 50]
print("Values greater than 50:", greater_than_50)
print()
even_arr = arr[arr%2==0]
print(even_arr)



Addition: [ 3  7 11 15]
Multiplication: [ 2 12 30 56]
Original array: [80 38 31 68 59 12 13 58 37 79 36 55 67 82 51]
Values greater than 50: [80 68 59 58 79 55 67 82 51]

[80 38 68 12 58 36 82]
